package rules;

import main.java.dsin.Objeto.*;
import main.java.dsin.Accion.*;
import main.java.dsin.Personaje.*;
import main.java.dsin.Estado.*;
// Creación de personajes sin estado
rule "0.01.1 Creación de Personajes Principales MITO1"
agenda-group "MITO1"
then
	//Mito 1
    insert(new Heroe(Constantes.PERSEO));
    insert(new Humano(Constantes.ANDROMEDA));
    insert(new Dios(Constantes.POSEIDON));
    insert(new Dios(Constantes.HADES));
    insert(new Dios(Constantes.ATENEA));
    insert(new Dios(Constantes.HERMES));
    insert(new Dios(Constantes.HEFESTO));
    insert(new Dios(Constantes.GRAYAS));
    insert(new Humano(Constantes.CASIOPEA));
    insert(new Criatura(Constantes.MEDUSA));
    insert(new Semidios(Constantes.LAS_NINFAS));
    insert(new Criatura(Constantes.CETO));
    insert(new Criatura(Constantes.GORGONAS));
    //Mito 2

end


rule "0.01.2 Creación de Personajes Principales MITO2"
agenda-group "MITO2"
then
    insert(new Heroe(Constantes.TESEO));
    insert(new Humano(Constantes.MINOS));
    insert(new Criatura(Constantes.MINOTAURO));
    insert(new Humano(Constantes.ARIADNA));
    insert(new Humano(Constantes.DEDALO));
    insert(new Humano(Constantes.ICARO));
end


rule "0.02.1 Creación de Objetos Especiales MITO1"
agenda-group "MITO1"
then
    insert(new Objeto(Constantes.ESCUDO_DE_BRONCE, Constantes.CAPACIDAD_REFLEXION));
    insert(new Objeto(Constantes.HOZ_DE_ACERO, Constantes.CAPACIDAD_MATAR));
    insert(new Objeto(Constantes.CASCO_DE_HADES, Constantes.CAPACIDAD_INVISIBILIDAD));
    insert(new Objeto(Constantes.ZURRON_MAGICO, Constantes.CAPACIDAD_GUARDAR_CABEZA_MEDUSA));
    insert(new Objeto(Constantes.SANDALIAS_ALADAS, Constantes.CAPACIDAD_VUELO));
    insert(new Objeto(Constantes.ESPADA_INDESTRUCTIBLE, Constantes.CAPACIDAD_MATAR));
    insert(new Objeto(Constantes.BRIDAS_DE_ORO, Constantes.CAPACIDAD_ATRAPAR_PEGASO));
    insert(new Objeto(Constantes.OJO_DE_GRAYAS, Constantes.CAPACIDAD_INTERCAMBIO_INFORMACION));
    insert(new Objeto(Constantes.ANILLO_DE_INVISIBILIDAD, Constantes.CAPACIDAD_INVISIBILIDAD));
    insert(new Objeto(Constantes.ESPEJO_DE_MANO, Constantes.CAPACIDAD_REFLEXION));
    insert(new Objeto(Constantes.CONJURO_DE_VUELO, Constantes.CAPACIDAD_VUELO));
    

end



rule "0.02.2 Creación de Objetos Especiales MITO2"
agenda-group "MITO2"
then
    insert(new Objeto(Constantes.HILO_ARIADNA, Constantes.CAPACIDAD_ESCAPAR));
    insert(new Objeto(Constantes.ESPADA_TESEO, Constantes.CAPACIDAD_MATAR));
    insert(new Objeto(Constantes.ALAS_ICARO_DEDALO, Constantes.CAPACIDAD_VUELO));
    insert(new Objeto(Constantes.CUERNO_MINOTAURO, Constantes.CAPACIDAD_MATAR));
end



// Asignación de estados iniciales a personajes mito1
rule "0.03.1 Estado inicial: Ceto Preso y Andromeda Libre - Heroe Libre y Casiopea Libre MITO1"
agenda-group "MITO1"
when
    $ceto : Criatura(nombre == Constantes.CETO)
    $andromeda : Humano(nombre == Constantes.ANDROMEDA)
    $h : Heroe()
    $casiopea : Humano(nombre == Constantes.CASIOPEA)
then
    insert(new Preso($ceto));        
    insert(new Libre($andromeda)); 
    insert(new Libre($h));      
    insert(new Libre($casiopea));  
end


rule "0.03.2 Estado inicial: Minotauro Preso y Dedalo e Icaro Libre - Heroe Libre y Aridadna Libre MITO2"
agenda-group "MITO2"
when
    $minotauro : Criatura(nombre == Constantes.MINOTAURO)
    $dedalo : Humano(nombre == Constantes.DEDALO)
    $icaro : Humano(nombre == Constantes.ICARO)
    $h : Heroe()
    $ariadna : Humano(nombre == Constantes.ARIADNA)
then
    insert(new Preso($minotauro));        
    insert(new Libre($dedalo));
    insert(new Libre($icaro)); 
    insert(new Libre($h));      
    insert(new Libre($ariadna));    
end


// Relaciones iniciales de posesión
rule "0.04.1 Relaciones Iniciales de Posesión MITO1"
agenda-group "MITO1"
when
    $hades : Dios(nombre == Constantes.HADES)
    $atenea : Dios(nombre == Constantes.ATENEA)
    $hermes : Dios(nombre == Constantes.HERMES)
    $hefesto : Dios(nombre == Constantes.HEFESTO)        
    $grayas : Dios(nombre == Constantes.GRAYAS)  
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)   
    
    $escudoBronce : Objeto(nombre == Constantes.ESCUDO_DE_BRONCE)
    $cascoHades : Objeto(nombre == Constantes.CASCO_DE_HADES)
    $hozAcero : Objeto(nombre == Constantes.HOZ_DE_ACERO)
    $espadaIndestructible : Objeto(nombre == Constantes.ESPADA_INDESTRUCTIBLE)
    $bridasOro : Objeto(nombre == Constantes.BRIDAS_DE_ORO)
    $ojoGrayas : Objeto(nombre == Constantes.OJO_DE_GRAYAS)
    $zurron : Objeto(nombre == Constantes.ZURRON_MAGICO)
    $sandalias : Objeto(nombre == Constantes.SANDALIAS_ALADAS)
then
    insert(new Poseer($hades, $cascoHades));   
    insert(new Poseer($hermes, $hozAcero));   
    insert(new Poseer($hefesto, $espadaIndestructible)); 
    insert(new Poseer($atenea, $escudoBronce));
    insert(new Poseer($hefesto, $bridasOro));
    insert(new Poseer($grayas, $ojoGrayas));
    insert(new Poseer($ninfas, $zurron));   
    insert(new Poseer($ninfas, $sandalias));   
end




// Relaciones iniciales de posesión
rule "0.04.2 Relaciones Iniciales de Posesión MITO2"
agenda-group "MITO2"
when
    $minotauro : Criatura(nombre == Constantes.MINOTAURO)
    $ariadna : Humano(nombre == Constantes.ARIADNA)
    $teseo : Heroe(nombre == Constantes.TESEO)  
    
    $cuerno : Objeto(nombre == Constantes.CUERNO_MINOTAURO) 
    $hilo :	Objeto(nombre == Constantes.HILO_ARIADNA)
    $espada : Objeto(nombre == Constantes.ESPADA_TESEO)

then
    insert(new Poseer($minotauro, $cuerno));   
    insert(new Poseer($ariadna, $hilo));   
    insert(new Poseer($teseo, $espada)); 
end



