package rules;

// Importación de clases
import java.util.List;
import main.java.dsin.Objeto.*;
import main.java.dsin.Accion.*;
import main.java.dsin.Personaje.*;
import main.java.dsin.Estado.*;

// Variable global para mensajes de salida
global List<String> mensajes;

// REGLAS GENERALES---------------------------------------------------------------------------------------------------------------------
	
	//CAMBIOS:
		/*
		 - Cambiar ninfas a semidiosas  - 
		 - Los personajes no se hacen retract, se meten en Muerto y se comprueba con no
		*/

//LOS ESTADOS Y ACCIONES DEBEN IR CON INSTANCIAS DE PERSONAJES


// Regla para quitar objetos de personajes
//
rule "Quitar Objeto"
when
    $s : Personaje()
    $o : Objeto()
    $posee : Poseer(sujeto == $s, poseido == $o)
    $quita : Quitar(sujeto == $s, quitado == $o)
then
    retract($posee);
    retract($quita);
end


rule "Lootear al asesinado" 
when 
	$sujeto : Personaje()
	$asesinado : Personaje()
	$asesina : Asesinar(sujeto == $sujeto, asesinado == $asesinado)
	$o : Poseer(sujeto==$asesinado)
	
then 
	//REGLAS PARA LOOTEAR
end

rule "Personaje asesina a otro" 
when 
	$sujeto : Personaje()
	$asesinado : Personaje()
	$asesina : Asesinar(sujeto == $sujeto, asesinado == $asesinado)
	
then 
	mensajes.add($asesinado.getNombre() +" ha muerto a manos de " + $asesinado.getNombre());
	insert(new Muerto($asesinado));
	retract($asesinado);
end



rule "Obtiene objeto por el favor de un dios"
when
    $heroe : Heroe()
    $dios : Dios()
    $objeto : Objeto()
    $poseeDios : Poseer(sujeto == $dios, poseido == $objeto)
    FavoreceA(sujeto == $dios, favorecido == $heroe)
then
    mensajes.add($heroe.getNombre() +" obtiene "+ $objeto.getNombre() +" debido al favor de "+ $dios.getNombre());
    retract($poseeDios)
    insert(new Poseer($heroe, $objeto));
    
end

//REGLAS SEMIESPECIFICAS---------------------------------------------------------------------------------------------------------------------

rule "Liberar a Andromeda con objeto de petrificación matando a Ceto"
when
    $perseo : Heroe(nombre == "Perseo")
    $ceto : Criatura(nombre == "Ceto")
    $andromeda : Humano(nombre == "Andromeda")
    $andromedaPresa : Preso(afectado == $andromeda)

    $objPetrificar : Objeto(capacidadDe == "Petrificacion")
    Poseer(sujeto == $perseo, poseido == $objPetrificar)
then
    mensajes.add("Perseo libera a Andromeda usando el/la "+$objPetrificar.getNombre()+" matando a Ceto.");
    insert(new Muerto($ceto));
    insert(new Libre($andromeda));
    retract($andromeda);
end





// REGLAS ESPECIFICAS ---------------------------------------------------------------------------------------------------------------------

rule "Enojo de Poseidon hacia Casiopea"
when
    $poseidon : Dios(nombre == "Poseidon")
    $casiopea : Humano(nombre == "Casiopea")
    $ceto : Criatura(nombre == "Ceto")
    $cetoPreso : Preso(afectado == $ceto) 

    TieneEnojoCon(sujeto == $poseidon, enojado == $casiopea)
then
    mensajes.add("Ceto queda libre debido al enojo de Poseidon hacia Casiopea.");
    retract($cetoPreso);
    insert(new Libre($ceto));
end

rule "Andromeda capturada por Ceto"
when
    $andromeda : Humano(nombre == "Andromeda")
    $ceto : Criatura(nombre == "Ceto")
    $andromedaLibre : Libre(afectado == $andromeda)
	$cetoLibre : Libre(afectado == $ceto)
then
    mensajes.add("Andrómeda queda presa debido a que Ceto está libre.");
    retract($andromedaLibre);
    insert(new Preso($andromeda));
end


rule "Liberar a Andromeda con Cabeza de Medusa matando a Ceto"
when
    $perseo : Heroe(nombre == "Perseo")
    $ceto : Criatura(nombre == "Ceto")
    $andromeda : Humano(nombre == "Andromeda")
    $andromedaPresa : Preso(afectado == $andromeda)

    $cabezaMedusa : Objeto(nombre == "Cabeza de medusa", capacidadDe == "Petrificacion")
    Poseer(sujeto == $perseo, poseido == $cabezaMedusa)
then
    mensajes.add("Perseo libera a Andromeda usando la Cabeza de Medusa matando a Ceto.");
    insert(new Muerto($ceto));
    insert(new Libre($andromeda));
end



rule "Obtiene Capacidad de Reflexión con Escudo Espejo"
when
    $perseo : Heroe(nombre == "Perseo")
    $hefesto : Dios(nombre == "Hefesto")
    $escudoBronce : Objeto(nombre == "Escudo de Bronce")
    Poseer(sujeto == $perseo, poseido == $escudoBronce)
    FavoreceA(sujeto == $hefesto, favorecido == $perseo)
then
    mensajes.add("Perseo obtiene el Escudo Espejo gracias al favor de Hefesto, que pule el Escudo de Bronce");
    insert(new Poseer($perseo ,new Objeto("Escudo Espejo", "Reflexion")));
    retract($escudoBronce);
    
    
end


rule "Localización de las Grayas por favores de Hermes y Atenea"
when
    $perseo : Heroe(nombre == "Perseo")
    $hermes : Dios(nombre == "Hermes")
    $atenea : Dios(nombre == "Atenea")
    $hades : Dios(nombre == "Hades")
    $grayas : Dios(nombre == "Grayas")
    FavoreceA(sujeto == $hermes, favorecido == $perseo)
    FavoreceA(sujeto == $atenea, favorecido == $perseo)
    FavoreceA(sujeto == $hades, favorecido == $perseo)
    
then
    mensajes.add("Perseo localiza a las Grayas debido a los favores de Hermes y Atenea.");
    insert(new Localizar($perseo, $grayas));
end


// CAMBIADA / DIVIDIDA para poder reutilizar
rule "Chantaje a las grayas para localizar a las ninfas"
when
    $heroe : Heroe()
    $grayas : Dios(nombre == "Grayas")
    $ojoGrayas : Objeto(nombre == "Ojo Grayas")
    $poseeOjo : Poseer(sujeto == $heroe, poseido == $ojoGrayas )
    $ninfas : Semidios(nombre == "Ninfas")
then
    mensajes.add($heroe.getNombre()+" localiza a las Ninfas tras chantajear a las Grayas");
    //Posible implementacion de intercambio???
    retract($poseeOjo);
    insert(new Poseer($grayas, $ojoGrayas));
    // 
    insert(new Localizar($heroe, $ninfas));
end

rule "Obtener ojo grayas"
when
	$heroe : Heroe()
	$grayas : Dios(nombre == "Grayas")
    $ojoGrayas : Objeto(nombre == "Ojo Grayas")
    $poseeOjo : Poseer(sujeto == $grayas, poseido == $ojoGrayas )
    $poseeInvvis : Poseer(sujeto == $heroe, poseido.CapacidadDe == "Invisibilidad")
then
	//Posible implementacion de nueva acción robar??
	insert( new Quitar($grayas, $ojoGrayas));
	insert(new Poseer($heroe, $ojoGrayas));
end
	
    



rule "Obtencion Sandalias y Zurron tras localizar Ninfas"
when
    $perseo : Heroe(nombre == "Perseo")
    $ninfas : Criatura(nombre == "Ninfas")
   	$medusa : Criatura(nombre == "Medusa")
    $zurronMagico : Objeto(nombre == "Zurron Magico")
    $sandaliasAladas : Objeto(nombre == "Sandalias Aladas")
    $ojoGrayas : Objeto(nombre == "Ojo de Grayas")
    $poseeNinfasZ : Poseer(sujeto == $ninfas, poseido == $zurronMagico)
    $poseeNinfasS : Poseer(sujeto == $ninfas, poseido == $sandaliasAladas)
    Poseer(sujeto == $perseo, poseido == $ojoGrayas)
    Localizar(sujeto == $perseo, persLocalizado == $ninfas )
then
    mensajes.add("Perseo localiza a las Ninfas tras el intercambio del Ojo de las Grayas. Obtiene el Zurron Magico y las Sandalias Aladas.");
    retract($poseeNinfasZ);
    retract($poseeNinfasS);
    insert(new Poseer($perseo, $zurronMagico));
    insert(new Poseer($perseo, $sandaliasAladas));
    insert(new Localizar($perseo, $medusa));
end


rule "Perseo mata a Medusa"
when
    $p : Heroe(nombre == "Perseo")
    $m : Criatura(nombre == "Medusa")
    
    $obj1 : Poseer(sujeto == $p, capacidadDe   == "Invisibilidad")
    $obj2 : Poseer(sujeto == $p, capacidadDe == "Vuelo")
    $obj3 : Poseer(sujeto == $p, capacidadDe == "Reflexion")
    $obj4 : Poseer(sujeto == $p, capacidadDe   == "Matar")
    Localizar(sujeto == $p, persLocalizado == $m)

then
    mensajes.add("Perseo mata a Medusa debido a tener Hoz de Acero, Espejo, Invisibilidad y Vuelo.");
    insert(new Muerto($m));
    retract($m);
end




rule "Muere debido a que no tiene el Zurron Magico"
when
	$perseo : Heroe(nombre == "Perseo")
	$medusa : Criatura(nombre == "Medusa")
	$medusaMuerta : Muerto(afectado == $medusa)
    $zurronMagico : Objeto(nombre == "Zurron Magico")
    not Poseer(sujeto == $perseo, poseido == $zurronMagico)
then
	mensajes.add("Perseo muerte al matar a Medusa y no guardar la cabeza en el Zurron Magico");
	retract($perseo);
end



rule "Mata a Ceto y libera a Andrómeda"
when
    $perseo : Heroe(nombre == "Perseo")
    $ceto : Criatura(nombre == "Ceto")
    $cetoLibre : Libre(afectado  == $ceto)
    $andromeda : Humano(nombre == "Andromeda")
	$andromedaPresa : Preso(afectado  == $andromeda)
    $cabezaMedusa : Objeto(nombre == "Cabeza de Medusa", capacidadDe == "Petrificacion")
    Poseer(sujeto == $perseo, poseido == $cabezaMedusa)
then
    mensajes.add("Perseo mata a Ceto usando la Cabeza de Medusa y libera a Andrómeda.");
    retract($andromedaPresa);
    retract($cetoLibre);
    insert(new Muerto($ceto));
    insert(new Libre($andromeda));
end


















// Queries to find specific Personajes and Objetos using helper methods
query "getPersonajeByName" (String name)
    $p : Personaje( nombre == name )
end

query "getObjetoByName" (String name)
    $o : Objeto( nombre == name )
end
