package rules;

// Importación de clases
import java.util.List;
import main.java.dsin.Objeto.*;
import main.java.dsin.Accion.*;
import main.java.dsin.Personaje.*;
import main.java.dsin.Estado.*;
import rules.Constantes;

// Variable global para mensajes de salida
global List<String> mensajes;

// REGLAS GENERALES---------------------------------------------------------------------------------------------------------------------
	
	//CAMBIOS: 
		/*
		 - Cambiar ninfas a semidiosas  - CHECK
	     - Generalizacion de heroe - CHECK
		 - Los personajes no se hacen retract, se meten en Muerto y se comprueba con no - 
		 - Regla lootear - 
		*/

//LOS ESTADOS Y ACCIONES DEBEN IR CON INSTANCIAS DE PERSONAJES


// Regla para quitar objetos de personajes
//
rule "Quitar Objeto"
when
    $s : Personaje()
    $o : Objeto()
    $posee : Poseer(sujeto == $s, poseido == $o)
    $quita : Quitar(sujeto == $s, quitado == $o)
then
    retract($posee);
    retract($quita);
end


rule "Lootear al asesinado" 
when 
	$sujeto : Personaje()
	$asesinado : Personaje()
	$asesina : Asesinar(sujeto == $sujeto, asesinado == $asesinado)
	$o : Poseer(sujeto==$asesinado)
	
then 
	//REGLAS PARA LOOTEAR
end

rule "Personaje asesina a otro" 
when 
	$sujeto : Personaje()
	$asesinado : Personaje()
	$asesina : Asesinar(sujeto == $sujeto, asesinado == $asesinado)
	
then 
	mensajes.add($asesinado.getNombre() +" ha muerto a manos de " + $asesinado.getNombre());
	insert(new Muerto($asesinado));
	retract($asesinado);
end



rule "Obtiene objeto por el favor de un dios"
when
    $heroe : Heroe()
    $dios : Dios()
    $objeto : Objeto()
    $poseeDios : Poseer(sujeto == $dios, poseido == $objeto)
    FavoreceA(sujeto == $dios, favorecido == $heroe)
then
    mensajes.add($heroe.getNombre() +" obtiene "+ $objeto.getNombre() +" debido al favor de "+ $dios.getNombre());
    retract($poseeDios)
    insert(new Poseer($heroe, $objeto));
    
end

//REGLAS SEMIESPECIFICAS---------------------------------------------------------------------------------------------------------------------

rule "Liberar a Andromeda con objeto de petrificación matando a Ceto"
when
    $heroe : Heroe()
    $ceto : Criatura(nombre == Constantes.CETO)
    $andromeda : Humano(nombre == Constantes.ANDROMEDA)
    $andromedaPresa : Preso(afectado == $andromeda)

    $objPetrificar : Objeto(capacidadDe == Constantes.CAPACIDAD_PETRIFICACION)
    Poseer(sujeto == $heroe, poseido == $objPetrificar)
then
    mensajes.add($heroe.getNombre() + " libera a Andromeda usando el/la "+$objPetrificar.getNombre()+" matando a Ceto.");
    insert(new Muerto($ceto));
    insert(new Libre($andromeda));
    retract($andromeda);
end





// REGLAS ESPECIFICAS ---------------------------------------------------------------------------------------------------------------------

rule "Enojo de Poseidon hacia Casiopea"
when
    $poseidon : Dios(nombre == Constantes.POSEIDON)
    $casiopea : Humano(nombre == Constantes.CASIOPEA)
    $ceto : Criatura(nombre == Constantes.CETO)
    $cetoPreso : Preso(afectado == $ceto) 

    TieneEnojoCon(sujeto == $poseidon, enojado == $casiopea)
then
    mensajes.add("Ceto queda libre debido al enojo de Poseidon hacia Casiopea.");
    retract($cetoPreso);
    insert(new Libre($ceto));
end

rule "Andromeda capturada por Ceto"
when
    $andromeda : Humano(nombre == Constantes.ANDROMEDA)
    $ceto : Criatura(nombre == Constantes.CETO)
    $andromedaLibre : Libre(afectado == $andromeda)
	$cetoLibre : Libre(afectado == $ceto)
then
    mensajes.add("Andrómeda queda presa debido a que Ceto está libre.");
    retract($andromedaLibre);
    insert(new Preso($andromeda));
end



rule "Obtiene Capacidad de Reflexión con Escudo Espejo"
when
    $heroe : Heroe()
    $hefesto : Dios(nombre == Constantes.HEFESTO)
    $escudoBronce : Objeto(nombre == Constantes.ESCUDO_DE_BRONCE)
    Poseer(sujeto == $heroe, poseido == $escudoBronce)
    FavoreceA(sujeto == $hefesto, favorecido == $heroe)
then
    mensajes.add( $heroe.getNombre() + " obtiene el Escudo Espejo gracias al favor de Hefesto, que pule el Escudo de Bronce");
    insert(new Poseer($heroe ,new Objeto("Escudo Espejo", "Reflexion")));
    retract($escudoBronce);
    
    
end


rule "Localización de las Grayas por favores de Hermes y Atenea"
when
    $heroe : Heroe()
    $hermes : Dios(nombre == Constantes.HERMES)
    $atenea : Dios(nombre == Constantes.ATENEA)
    $hades : Dios(nombre == Constantes.HADES)
    $grayas : Dios(nombre == Constantes.GRAYAS)
    FavoreceA(sujeto == $hermes, favorecido == $heroe)
    FavoreceA(sujeto == $atenea, favorecido == $heroe)
    FavoreceA(sujeto == $hades, favorecido == $heroe)
    
then
    mensajes.add($heroe.getNombre() + " localiza a las Grayas debido a los favores de Hermes y Atenea.");
    insert(new Localizar($heroe, $grayas));
end


// CAMBIADA / DIVIDIDA para poder reutilizar
rule "Chantaje a las grayas para localizar a las ninfas"
when
    $heroe : Heroe()
    $grayas : Dios(nombre == Constantes.GRAYAS)
    $ojoGrayas : Objeto(nombre == Constantes.OJO_DE_GRAYAS)
    $poseeOjo : Poseer(sujeto == $heroe, poseido == $ojoGrayas )
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)
then
    mensajes.add($heroe.getNombre()+" localiza a las Ninfas tras chantajear a las Grayas");
    //Posible implementacion de intercambio???
    retract($poseeOjo);
    insert(new Poseer($grayas, $ojoGrayas));
    insert(new Localizar($heroe, $ninfas));
end

rule "Obtener ojo grayas"
when
	$heroe : Heroe()
	$ninfas : Semidios(nombre == Constantes.LAS_NINFAS)
	$grayas : Dios(nombre == Constantes.GRAYAS)
    $ojoGrayas : Objeto(nombre == Constantes.OJO_DE_GRAYAS)
    $poseeOjo : Poseer(sujeto == $grayas, poseido == $ojoGrayas )
    Poseer(sujeto == $heroe, capacidadDe  == Constantes.CAPACIDAD_INVISIBILIDAD)
    not Localizar(sujeto == $heroe, persLocalizado == $ninfas)
then
	mensajes.add($heroe.getNombre()+" roba el ojo a las Grayas.");
	retract($poseeOjo);
	insert(new Poseer($heroe, $ojoGrayas));
end
	
    


rule "Obtencion Sandalias Aladas tras localizar Ninfas"
when
    $heroe : Heroe()
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)
   	$medusa : Criatura(nombre == Constantes.MEDUSA)
    $sandaliasAladas : Objeto(nombre == Constantes.SANDALIAS_ALADAS)
    $poseeNinfasS : Poseer(sujeto == $ninfas, poseido == $sandaliasAladas)
    Localizar(sujeto == $heroe, persLocalizado == $ninfas )
then
    mensajes.add($heroe.getNombre() + " localiza a las Ninfas tras el intercambio del Ojo de las Grayas. Obtiene las Sandalias Aladas.");
    retract($poseeNinfasS);
    insert(new Poseer($heroe, $sandaliasAladas));
    //insert(new Localizar($heroe, $medusa));
end



rule "Obtencion Zurron Magico tras localizar Ninfas"
when
    $heroe : Heroe()
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)
   	$medusa : Criatura(nombre == Constantes.MEDUSA)
    $zurronMagico : Objeto(nombre == Constantes.ZURRON_MAGICO)
    $poseeNinfasZ : Poseer(sujeto == $ninfas, poseido == $zurronMagico)
    Localizar(sujeto == $heroe, persLocalizado == $ninfas )
then
    mensajes.add($heroe.getNombre() + " localiza a las Ninfas tras el intercambio del Ojo de las Grayas. Obtiene el Zurron Magico");
    retract($poseeNinfasZ);
    insert(new Poseer($heroe, $zurronMagico));
    //insert(new Localizar($heroe, $medusa));
end





rule "Heroe evita  a las gorgonas"
when
then
end



rule "Perseo mata a Medusa"
when
    $heroe : Heroe()
    $m : Criatura(nombre == "Medusa")
    
    $obj1 : Poseer(sujeto == $heroe, capacidadDe   == Constantes.CAPACIDAD_INVISIBILIDAD)
    $obj2 : Poseer(sujeto == $heroe, capacidadDe == Constantes.CAPACIDAD_VUELO)
    $obj3 : Poseer(sujeto == $heroe, capacidadDe == Constantes.CAPACIDAD_REFLEXION)
    $obj4 : Poseer(sujeto == $heroe, capacidadDe   == Constantes.CAPACIDAD_MATAR)
    //Localizar(sujeto == $heroe, persLocalizado == $m)
    not Muerto(afectado == $m)

then
	String objetos  = $obj1.getNombre() + ", " + $obj2.getNombre() + ", "+ $obj3.getNombre() + " y "+ $obj4.getNombre();
    mensajes.add($heroe.getNombre() + " mata a Medusa debido a tener " + objetos);
    insert(new Poseer($heroe, new Objeto(Constantes.CABEZA_DE_MEDUSA, Constantes.CAPACIDAD_PETRIFICACION)));
    insert(new Muerto($m));
end




rule "Muere debido a que no tiene el Zurron Magico"
when
	$heroe : Heroe()
	$medusa : Criatura(nombre == Constantes.MEDUSA)
	$medusaMuerta : Muerto(afectado == $medusa)
    $zurronMagico : Objeto(nombre == Constantes.ZURRON_MAGICO)
    not Poseer(sujeto == $heroe, poseido == $zurronMagico)
then
	mensajes.add($heroe.getNombre() + " muerte al matar a Medusa y no guardar la cabeza en el Zurron Magico");
	retract($heroe);
end



rule "Mata a Ceto y libera a Andrómeda"
when
    $heroe : Heroe()
    $ceto : Criatura(nombre == Constantes.CETO)
    $cetoLibre : Libre(afectado  == $ceto)
    $andromeda : Humano(nombre == Constantes.ANDROMEDA)
	$andromedaPresa : Preso(afectado  == $andromeda)
    $petrificar : Objeto(capacidadDe == Constantes.CAPACIDAD_PETRIFICACION)
    Poseer(sujeto == $heroe, poseido == $petrificar)
then
    mensajes.add("Perseo mata a Ceto usando la Cabeza de Medusa y libera a Andrómeda.");
    retract($andromedaPresa);
    retract($cetoLibre);
    insert(new Muerto($ceto));
    insert(new Libre($andromeda));
end


















// Queries to find specific Personajes and Objetos using helper methods
query "getPersonajeByName" (String name)
    $p : Personaje( nombre == name )
end

query "getObjetoByName" (String name)
    $o : Objeto( nombre == name )
end
