package rules;

// Importación de clases
import java.util.List;
import main.java.dsin.Objeto.*;
import main.java.dsin.Accion.*;
import main.java.dsin.Personaje.*;
import main.java.dsin.Estado.*;
import rules.Constantes;

// Variable global para mensajes de salida
global List<String> mensajes;

// REGLAS GENERALES---------------------------------------------------------------------------------------------------------------------
	
	//CAMBIOS: 
		/*
		 - Cambiar ninfas a semidiosas  - CHECK
	     - Generalizacion de heroe - CHECK
		 - Los personajes no se hacen retract, se meten en Muerto y se comprueba con no - CHECK
		 - Regla lootear - 
		*/
	//TODO 
		/*
		-tenemos que implementar la clase apresar, es necersaria para la pase 3
		-generalizar mas reglas para poder mezclar los mitos
		-TERMINAR LOOTEAR!!!!!!
		*/

//LOS ESTADOS Y ACCIONES DEBEN IR CON INSTANCIAS DE PERSONAJES


// REGLAS PARA ACCIONES GENERALES
//
rule "Quitar Objeto"
when
    $s : Personaje()
    $o : Objeto()
    $posee : Poseer(sujeto == $s, poseido == $o)
    $quita : Quitar(sujeto == $s, quitado == $o)
then
    retract($posee);
    retract($quita);
end


rule "Lootear al asesinado" 
when 
	$sujeto : Personaje()
	$asesinado : Personaje()
	$asesina : Asesinar(sujeto == $sujeto, asesinado == $asesinado)
	$o : Poseer(sujeto==$asesinado)
	
then 
	//REGLAS PARA LOOTEAR
end

rule "Personaje asesina a otro" 
when 
	$sujeto : Personaje()
	$asesinado : Personaje()
	$asesina : Asesinar(sujeto == $sujeto, asesinado == $asesinado)
	
then 
	mensajes.add($asesinado.getNombre() +" ha muerto a manos de " + $sujeto.getNombre()+ ".");
	insert(new Muerto($asesinado));
	//REGLAS PARA LOOTEAR
end



rule "Obtiene objeto por el favor de un dios"
when
    $heroe : Heroe()
    $dios : Dios()
    $objeto : Objeto()
    $poseeDios : Poseer(sujeto == $dios, poseido == $objeto)
    FavoreceA(sujeto == $dios, favorecido == $heroe)
then
    mensajes.add($heroe.getNombre() +" obtiene "+ $objeto.getNombre() +" debido al favor de "+ $dios.getNombre()+ ".");
    retract($poseeDios)
    insert(new Poseer($heroe, $objeto));
    
end


rule "Heroe muere"
when
	$sujeto : Heroe()
	$muerto : Muerto(afectado == $sujeto)
then
	mensajes.add($sujeto.getNombre() + " no ha conseguido su objetivo. Fin de la historia.");
	retract($sujeto);
end



// REGLAS ESPECIFICAS ---------------------------------------------------------------------------------------------------------------------

rule "Enojo de Poseidon hacia Casiopea"
when
    $poseidon : Dios(nombre == Constantes.POSEIDON)
    $casiopea : Humano(nombre == Constantes.CASIOPEA)
    $casiopeaLibre : Libre(afectado == $casiopea)
    $ceto : Criatura(nombre == Constantes.CETO)
    $cetoPreso : Preso(afectado == $ceto) 

    TieneEnojoCon(sujeto == $poseidon, enojado == $casiopea)
then
    mensajes.add("Ceto queda libre debido al enojo de Poseidon hacia Casiopea.");
    retract($cetoPreso);
    insert(new Libre($ceto));
end

rule "Andromeda capturada por Ceto"
when
    $andromeda : Humano(nombre == Constantes.ANDROMEDA)
    $ceto : Criatura(nombre == Constantes.CETO)
    $andromedaLibre : Libre(afectado == $andromeda)
	$cetoLibre : Libre(afectado == $ceto)
	not Muerto( afectado ==  $ceto )
then
    mensajes.add("Andromeda queda presa debido a que Ceto esta libre y la captura.");
    retract($andromedaLibre);
    insert(new Preso($andromeda));
end


/* 	ELIMINAR?? El escudo de bronce damos por supuesto que ya esta pulido y refleja

rule "Obtiene Capacidad de Reflexión con Escudo Espejo"
when
    $heroe : Heroe()
    $hefesto : Dios(nombre == Constantes.HEFESTO)
    $escudoBronce : Objeto(nombre == Constantes.ESCUDO_DE_BRONCE)
    Poseer(sujeto == $heroe, poseido == $escudoBronce)
    FavoreceA(sujeto == $hefesto, favorecido == $heroe)
then
    mensajes.add( $heroe.getNombre() + " obtiene el Escudo Espejo gracias al favor de Hefesto, que pule el Escudo de Bronce.");
    insert(new Poseer($heroe ,new Objeto("Escudo Espejo", "Reflexion")));
    retract($escudoBronce);
    
    
end
*/

rule "Localización de las Grayas por favores de Hermes y Atenea"
when
    $heroe : Heroe()
    $hermes : Dios(nombre == Constantes.HERMES)
    $atenea : Dios(nombre == Constantes.ATENEA)
    $hades : Dios(nombre == Constantes.HADES)
    $grayas : Dios(nombre == Constantes.GRAYAS)
    FavoreceA(sujeto == $hermes, favorecido == $heroe)
    FavoreceA(sujeto == $atenea, favorecido == $heroe)
    FavoreceA(sujeto == $hades, favorecido == $heroe)
    
then
    mensajes.add($heroe.getNombre() + " localiza a las Grayas debido a los favores de Hermes y Atenea.");
    insert(new Localizar($heroe, $grayas));
end


// CAMBIADA / DIVIDIDA para poder reutilizar
rule "Chantaje a las grayas para localizar a las ninfas"
when
    $heroe : Heroe()
    $grayas : Dios(nombre == Constantes.GRAYAS)
    $gorgonas : Criatura(nombre == Constantes.GORGONAS)
    $ojoGrayas : Objeto(nombre == Constantes.OJO_DE_GRAYAS)
    $poseeOjo : Poseer(sujeto == $heroe, poseido == $ojoGrayas )
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)   	
    $medusa : Criatura(nombre == Constantes.MEDUSA)
then
    mensajes.add($heroe.getNombre()+" localiza a las Ninfas y a Medusa tras chantajear a las Grayas ");
    //Posible implementacion de intercambio???
    retract($poseeOjo);
    //insert(new Poseer($grayas, $ojoGrayas)); es realmente necesario para la historia devolverselo? si no lo devolvemos evitamos el bucle
    insert(new Localizar($heroe, $ninfas));
    insert(new Localizar($heroe, $medusa));
end

rule "Obtener ojo grayas"
when
	$heroe : Heroe()
	$grayas : Dios(nombre == Constantes.GRAYAS)
	Localizar(sujeto == $heroe, persLocalizado == $grayas)
    $ojoGrayas : Objeto(nombre == Constantes.OJO_DE_GRAYAS)
    $poseeOjo : Poseer(sujeto == $grayas, poseido == $ojoGrayas )
    Poseer(sujeto == $heroe, capacidadDe  == Constantes.CAPACIDAD_INVISIBILIDAD)
then
	mensajes.add($heroe.getNombre()+" roba el ojo a las Grayas.");
	retract($poseeOjo);
	insert(new Poseer($heroe, $ojoGrayas));
end
	
    


rule "Obtencion Sandalias Aladas tras localizar Ninfas"
when
    $heroe : Heroe()
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)
   	$medusa : Criatura(nombre == Constantes.MEDUSA)
    $sandaliasAladas : Objeto(nombre == Constantes.SANDALIAS_ALADAS)
    $poseeNinfasS : Poseer(sujeto == $ninfas, poseido == $sandaliasAladas)
    Localizar(sujeto == $heroe, persLocalizado == $ninfas )
    not Muerto(afectado == $medusa)
then
    mensajes.add($heroe.getNombre() + " recibe de las Ninfas las Sandalias Aladas.");
    retract($poseeNinfasS);
    insert(new Poseer($heroe, $sandaliasAladas));
    //insert(new Localizar($heroe, $medusa));
end



rule "Obtencion Zurron Magico tras localizar Ninfas"
when
    $heroe : Heroe()
    $ninfas : Semidios(nombre == Constantes.LAS_NINFAS)
   	$medusa : Criatura(nombre == Constantes.MEDUSA)
    $zurronMagico : Objeto(nombre == Constantes.ZURRON_MAGICO)
    $poseeNinfasZ : Poseer(sujeto == $ninfas, poseido == $zurronMagico)
    Localizar(sujeto == $heroe, persLocalizado == $ninfas )
    not Muerto(afectado == $medusa)
    
then
    mensajes.add($heroe.getNombre() + " recibe de las Ninfas el Zurron Magico.");
    retract($poseeNinfasZ);
    insert(new Poseer($heroe, $zurronMagico));
end





//SUPERAR O MORIR, GORGONAS
rule "Heroe evita  a las gorgonas"
when
	    $heroe : Heroe()
	    $g : Criatura(nombre == Constantes.GORGONAS)
	    $medusa : Criatura(nombre == Constantes.MEDUSA)
	    Localizar(sujeto==$heroe , persLocalizado==$medusa)
	 
	    $obj1 : Poseer(sujeto == $heroe, capacidadDe   == Constantes.CAPACIDAD_INVISIBILIDAD)
	    not Muerto(afectado == $g)
then
		mensajes.add($heroe.getNombre() + " evita a las Gorgonas y entra a la cueva gracias a tener "+ $obj1.getNombre() + ".");
		insert(new Muerto($g)); //Las ponemos en muerto aunque tecnicamenete no lo esten para evitar que se vuelva a disparar esta regla
		
end

rule "Heroe no evita  a las gorgonas"
when
	    $heroe : Heroe()
	    $g : Criatura(nombre == Constantes.GORGONAS)
	   	$medusa : Criatura(nombre == Constantes.MEDUSA)
	    Localizar(sujeto==$heroe , persLocalizado==$medusa)
	 
	    not Poseer(sujeto == $heroe, capacidadDe   == Constantes.CAPACIDAD_INVISIBILIDAD)
	    not Muerto(afectado == $g)
then
		mensajes.add($heroe.getNombre() + " no consigue evitar a las Gorgonas debido a no tener un objeto que lo haga invisible.");
		insert(new Muerto($heroe)); 
end


//SUPERAR O MORIR, MEDUSA
rule "Heroe mata a Medusa"
when
    $heroe : Heroe()
    $m : Criatura(nombre == Constantes.MEDUSA)
    $g : Criatura(nombre == Constantes.GORGONAS)
    Muerto(afectado == $g)			//Tiene que haberlas superado para llegar a medusa
    Localizar(sujeto==$heroe, persLocalizado==$m)
    $vuelo : Poseer(sujeto == $heroe, capacidadDe == Constantes.CAPACIDAD_VUELO)
    $obj3 : Poseer(sujeto == $heroe, capacidadDe == Constantes.CAPACIDAD_REFLEXION)
    $obj4 : Poseer(sujeto == $heroe, capacidadDe   == Constantes.CAPACIDAD_MATAR)
    not Muerto(afectado == $m)

then
	String objetos  =  $obj3.getNombre() + " y "+ $obj4.getNombre();
    mensajes.add($heroe.getNombre() + " mata a Medusa debido a tener " + objetos + " y vuelve a casa volando gracias a "+$vuelo.getNombre());
    insert(new Asesinar($heroe, $m));
    //SI HACEMOS LOOTEAR SE QUITA
    insert(new Poseer($heroe, new Objeto(Constantes.CABEZA_DE_MEDUSA, Constantes.CAPACIDAD_PETRIFICACION)));
end

rule "Lo mata medusa debido a que no tiene objeto reflexion"
when
	$heroe : Heroe()
	$medusa : Criatura(nombre == Constantes.MEDUSA)
	$g : Criatura(nombre == Constantes.GORGONAS)
	Muerto(afectado == $g)
	Localizar(sujeto==$heroe, persLocalizado==$medusa)
    $reflejo : Objeto(capacidadDe == Constantes.CAPACIDAD_REFLEXION)
    not Poseer(sujeto == $heroe, poseido == $reflejo)
    not Muerto(afectado==$medusa)
then
	mensajes.add($heroe.getNombre() + " petrificado por Medusa debido a no tener un objeto que refleje");
	insert(new Asesinar($medusa,$heroe));

end

rule "Lo mata medusa debido a que no tiene objeto matar"
when
	$heroe : Heroe()
	$medusa : Criatura(nombre == Constantes.MEDUSA)
	$g : Criatura(nombre == Constantes.GORGONAS)
	Muerto(afectado == $g)			
	Localizar(sujeto==$heroe, persLocalizado==$medusa)
    $matar : Objeto(capacidadDe == Constantes.CAPACIDAD_MATAR)
    not Poseer(sujeto == $heroe, poseido == $matar)
    not Muerto(afectado==$medusa)
then
	mensajes.add($heroe.getNombre() + " muerte al intentar matar a Medusa ya que no posee un objeto con dicha capacidad");
	insert(new Asesinar($medusa,$heroe));

end


rule "Muere debido a que no tiene el Zurron Magico"
when
	$heroe : Heroe()
	$medusa : Criatura(nombre == Constantes.MEDUSA)
	$asesinar: Asesinar(sujeto==$heroe, asesinado==$medusa)
	$medusaMuerta : Muerto(afectado == $medusa)
    $zurronMagico : Objeto(nombre == Constantes.ZURRON_MAGICO)
    not Poseer(sujeto == $heroe, poseido == $zurronMagico)
then
	mensajes.add($heroe.getNombre() + " muerte al matar a Medusa y no guardar la cabeza en el Zurron Magico.");
	insert(new Asesinar($medusa,$heroe));
end

rule "No puede volver a casa tras matar a Medusa"
when
	$heroe : Heroe()
	$medusa : Criatura(nombre == Constantes.MEDUSA)
	$asesinar: Asesinar(sujeto==$heroe, asesinado==$medusa)
	$medusaMuerta : Muerto(afectado == $medusa)
    not Poseer(sujeto == $heroe, poseido.capacidadDe == Constantes.CAPACIDAD_VUELO)
then
	mensajes.add($heroe.getNombre() + " nunca consiguio volver a casa al no poder volar y acabo muriendo de inanición");
	insert(new Muerto($heroe));
end





rule "Liberar a Andromeda con objeto de petrificación matando a Ceto"
when
    $heroe : Heroe()
    $ceto : Criatura(nombre == Constantes.CETO)
    $cetoLibre : Libre(afectado  == $ceto) 
    $andromeda : Humano(nombre == Constantes.ANDROMEDA)
    $andromedaPresa : Preso(afectado == $andromeda)
    $objPetrificar : Poseer(sujeto == $heroe, capacidadDe== Constantes.CAPACIDAD_PETRIFICACION)
    not Muerto( afectado == $ceto )
then
    mensajes.add($heroe.getNombre() + " libera a Andromeda usando la "+$objPetrificar.getNombre()+" matando a Ceto.");
    insert(new Asesinar($heroe, $ceto));
    insert(new Libre($andromeda));
end




















// Queries to find specific Personajes and Objetos using helper methods
query "getPersonajeByName" (String name)
    $p : Personaje( nombre == name )
end

query "getObjetoByName" (String name)
    $o : Objeto( nombre == name )
end
